### ISSUE TITLE
Inconsistency error in docs

### ISSUE THREAD

**Issue by megawubs** [spatie/laravel-event-projector#100]
In the docs (https://docs.spatie.be/laravel-event-projector/v1/basic-usage/handling-side-effects-using-reactors) the code example for the `BigAmountAddedReactor` uses `find()` instead of the `uuid()` method, as the `MoneyAdded` only receives the uuid.

so in short: `$account = Account::find($event->accountId);` should be `$account = Account::uuid($event->accountUuid);`

I tried searching for the docs on github to create a pull request, but i couldn't find it. That's why i created this issue.

**Comment by freekmurze** [comment]
Nice catch. There's an edit button on top of every page in our docs. Click it to easily create a PR.

**Comment by megawubs** [comment]
🤦‍♂️ How could i miss that! I'll make a PR
