### ISSUE TITLE
Is there an easy way to display an index of events in blade views?

### ISSUE THREAD

**Issue by laassseeee** [spatie/laravel-event-projector#101]
Is there an easy way to display the event history for a particular model in blade views, with all the value/status updates leading up to the current status, with timestamps?

**Comment by sebastiandedeyne** [comment]
You can query the `stored_events` table.

```php
DB::table('stored_events')
    ->where('condition_that_matches_model', $modelId)
    ->get();
```

You could also create a `StoredEvent` eloquent model and query that one.
