### ISSUE TITLE
laravel timestamps in models will be incorrect if left unhandled

### ISSUE THREAD

**Issue by nirradi** [spatie/laravel-event-projector#104]
I'm not sure if this is a feature request or a documentation bug. 

If you add timestamps to your models that are updated via a projection, then the timestamps will be populated by the insertion to your database rather than when the event happened. This can be slightly off if using a queue to handle events and grossly incorrect when replaying the events.

I suggest either stating this in the documentation and warning the users to not use timestamps or add the appropriate handling 

OR

maybe add a trait that when present, will copy the event->created_at timestamp to the correct (updated_at or created_at or deleted_at) timestamp. 

Thoughts?

**Comment by fgilio** [comment]
Yep, this is something to keep in mind. We solved it by recording the timestamps in the event meta, and then using that when projecting the state.
A trait would be handy.

**Comment by freekmurze** [comment]
I'd welcome a PR to the docs with a warning.
