### ISSUE TITLE
Event projector not receiving events

### ISSUE THREAD

**Issue by ankush981** [spatie/laravel-event-projector#106]
Hello, first of all thanks a lot for this awesome package! I heard about event sourcing recently and am happy that there's already something readymade for Laravel. Anyway, on to my question:

I have a very simple event class for firing events when someone logs into the app. This uses the default auth, so there isn't anything for the projector to do as such, but I wanted to just have the event logged:

```
<?php

namespace App\Projectors\Common;

use Spatie\EventProjector\Projectors\Projector;
use Spatie\EventProjector\Projectors\ProjectsEvents;
use Illuminate\Support\Facades\Log;

use App\Events\Common\LoggedIn;

class LoggedInProjector implements Projector
{
    use ProjectsEvents;

    protected $handlesEvents = [
        LoggedIn::class => 'onLoggedIn',
    ];

    public function onLoggedIn(LoggedIn $event)
    {
        Log::info('Damn, someone logged in!');
        echo 'Damn, someone logged in!';
    }
}
```
As you can see, I'm logging and echoing a string as "proof" that this projector is receiving events. I do believe I have Redis set up correctly (the name of the queue being `all_events`), as I can see the events stored in Redis and then disappear when I run the worker.

```
hrms-ait$ php artisan tinker
Psy Shell v0.9.9 (PHP 7.2.10-0ubuntu0.18.04.1 — cli) by Justin Hileman
>>> use App\Events\Common\LoggedIn;
>>> event(new LoggedIn(['user_id' => 7, 'role' => 'a3']));
=> [
     null,
   ]
```
This now gets stored in the `stored_events` table. Then I run the worker:

```
hrms-ait$ php artisan queue:work --queue=all_events
[2018-11-02 17:14:14][VhgW0a5jVhA7nMaleYRy0XYQyX3fJXRf] Processing: Spatie\EventProjector\HandleStoredEventJob
[2018-11-02 17:14:14][VhgW0a5jVhA7nMaleYRy0XYQyX3fJXRf] Processed:  Spatie\EventProjector\HandleStoredEventJob
```

And yet, there's no logging and no echo anywhere. Looks like the projector didn't receive anything:

```
mysql> select * from projector_statuses \G
*************************** 1. row ***************************
                     id: 1
         projector_name: App\Projectors\Common\LoggedInProjector
                 stream: main
has_received_all_events: 0
last_processed_event_id: 0
             created_at: 2018-11-02 15:09:12
             updated_at: 2018-11-02 15:09:12
1 row in set (0.00 sec)
```
. . . even though I have my projector registered in `config/event-projector.php`:

```
'projectors' => [
        App\Projectors\Common\LoggedInProjector::class,
    ],
```
Even if I not register my projector, I get the same behavior as before, so I daresay the projector isn't receiving the events. Any idea why this might be?

Thanks so much in advance!

**Comment by freekmurze** [comment]
The package tracks which events are already handled. It will not call the projector a second them for the same event.

Take a look at the content op the `projector_statuses` table.
