### ISSUE TITLE
Error Setting Up Using the Documentation

### ISSUE THREAD

**Issue by chrisidakwo** [spatie/laravel-event-projector#111]
After following the example in documentation, I tried using tinker to test and came up with this error:
`Spatie/EventProjector/Exceptions/InvalidStoredEvent with message "Failed to unserialize an event with class App/Events/CompanyCreatedEvent on stored event with id "7". Are you sure that event class exists?"`

The only thing that seems different from the example is that I'm not using uuid, rather a field from the request data. The field is unique for each entry and is provided by the user, hence can be used to query the DB for a specific entry.

Here is the CompanyCreatedEvent class:
`class CompanyCreatedEvent implements ShouldBeStored {
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * @var array
     */
    public $companyAttributes;

    /**
     * Create a new event instance.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes) {
        $this->companyAttributes = $attributes;
    }
}`

and here is the Company model:
`
class Company extends BaseModel {
    use SoftDeletes;

    protected $fillable = ["name", "domain", "slogan", "phones", "logo", "is_enabled"];
    protected $dates = ["deleted_at"];
    protected $casts = ["is_enabled" => "bool"];

    /**
     * Returns the customer phone numbers as an array
     *
     * @return array
     */
    public function getPhonesArray() {
        return explode(",", $this->phones);
    }

    /**
     * @param array $attributes
     * @return Company
     */
    public static function createWithAttributes(array $attributes) {
        event(new CompanyCreatedEvent($attributes));

        return static::domain($attributes["domain"]);
    }

    public function remove() {
        event(new CompanyDeletedEvent($this->id));
    }

    /**
     * @param array $attributes
     * @return Company
     */
    public static function updateWithAttributes(array $attributes) {
        event(new CompanyUpdatedEvent($attributes));

        return static::find($attributes["id"])->first();
    }

    /**
     * @param string $domain
     * @return Company
     */
    public static function domain(string $domain) {
        return static::where("domain", $domain)->first();
    }
}
`

**Comment by chrisidakwo** [comment]
Similar issue when I run from the browser

**Comment by sebastiandedeyne** [comment]
That exception gets thrown here: https://github.com/spatie/laravel-event-projector/blob/d8c5ebc50e22ac77239f3daad25084b92f23f971/src/Models/StoredEvent.php#L45-L52

Could you maybe add some logging to see the actual exception?

**Comment by sebastiandedeyne** [comment]
Feel free to open a new issue with additional error logs.

**Comment by Jnesselr** [comment]
Your issue is that the constructor attribute is named "$attributes" and the field is named "$companyAttributes". When it gets serialized, the field is named "companyAttributes", but when it gets deserialized, companyAttributes doesn't match a constructor parameter and it fails.

I just ran across this myself, and it's not super intuitive that the attribute field must match the constructor name.
