### ISSUE TITLE
What happens if I accidentally use rerun with some accounts already existing?

### ISSUE THREAD

**Issue by mathewparet** [spatie/laravel-event-projector#113]

**Comment by sebastiandedeyne** [comment]
Probably nothing good :D

It depends on your app really. If you rerun a `CreateAccount` event some how, you'll probably run into an integrity constraint in your database. If you update an account twice, the values might not be correct anymore.

Our package will never rerun things by itself though, the only thing I can say here is handle the artisan commands with care on production.
