### ISSUE TITLE
When queuing how do handle balances in case of delayed executions in queue

### ISSUE THREAD

**Issue by mathewparet** [spatie/laravel-event-projector#114]
Consider Mary has an account balance of $100

She uses her website wallet to buy item A worth $100 in one order
She then buys another item B worth $100 in another order.

Now consider there is a slight backlog in the queue (a couple of seconds maybe).
Now I fire an event for order A. Since it is an event, control goes back to customer on the front end and she still sees a balance of $100 (since its not time for her queue item yet). This gives wrong impression to the customer.

How do we tackle such a scenario?

**Comment by sebastiandedeyne** [comment]
By default, all events are handled synchronously. The only solution here is don't use a queue, this problem applies to any app using queues, not just event sourced systems.

If performance is an issue, you could do the critical stuff in the event handler, and dispatch a job for other, more performance heavy things that need to be handled.
