### ISSUE TITLE
Projectors stops working after bulk updates

### ISSUE THREAD

**Issue by TomBrouwer** [spatie/laravel-event-projector#115]
Hi!

We implemented your package to store events and project them. It's working fine until we do multiple updates on the same model (different instances). It will stop project the events. Die projector status is set to a event ID which is not the last one. We don't get any errors or exceptions. It stops projecting. Three projectors (from 10) has the status for the "has_received_all_events" at false. What can be te problem here?

**Comment by fgilio** [comment]
Are you using a queue to handle the events? If not, try with that. Horizon works **great** with this package

**Comment by freekmurze** [comment]
If a lot of events are happening concurrently projectors may fall behind. Here's some more info on that: https://docs.spatie.be/laravel-event-projector/v1/basic-usage/making-sure-events-get-handled-in-the-right-order

Like @fgilio mentioned, queuing can solve this problem. Take a look at the docs, and let us know it that helps you.
