### ISSUE TITLE
event(AccountCreated) with "Queue + QueueProjector" failed right from the start.

### ISSUE THREAD

**Issue by cirdog** [spatie/laravel-event-projector#116]
```
FatalThrowableError (E_RECOVERABLE_ERROR)
Return value of Modules\Accounting\Models\Account::createWithAttributes() must be an instance of Modules\Accounting\Models\Account, null returned
```
If I "Create Account" with Queue (database driver) **AND** QueueProjector (AccountBalanceProjector) right from the start, it fails. However it will succeed if they are **NOT BOTH** active.
```
public static function createWithAttributes(array $attributes): Account
    {
        $attributes['uuid'] = (string) Uuid::uuid4();

        event(new AccountCreated($attributes));

        return static::uuid($attributes['uuid']);
    }
```
The queued event "AccountCreated" probably hasn't yet inserted the record at the time when "return uuid" executes, therefore the query returns "null" and throws exception on mismatched return type.

```
public $handlesEvents = [
        AccountCreated::class => 'onAccountCreated',
        MoneyAdded::class => 'onMoneyAdded',
        MoneySubtracted::class => 'onMoneySubtracted',
        AccountClosed::class => 'onAccountDeleted',
        BrokeMailSent::class => 'onBrokeMailSent'
    ];
```
Whether or not to use Queue depends on the QueueProjector interface but this hint affects all events under the projector. It seems that Account::createWithAttributes() is not queue-compatible.

Is there any recommended way of dealing with this kind of use cases? It seems to me a really common usage. Thanks!!

**Comment by lukio3** [comment]
Hi @cirdog

I encountered the same issue - Any projector where a synchronous operation is required cannot use QueuedProjector. It also took me a while to ascertain this from the docs. 

I simply have a separate Projector for purely the AccountCreated event and a second Projector for other events e.g BalanceAdded.

The second projector implements Queued Projector as a synchronous operation is not required.

Lukio3
