### ISSUE TITLE
Help with projector status and rebuilding

### ISSUE THREAD

**Issue by roarkmccolgan** [spatie/laravel-event-projector#120]
Hi Guys,

Firstly, thank you for a great product you have made. Really lucky to have you guys around.
I would like to get some clarification on how it actually works :)

For background, I am using the AccountBalance projector example from the docs.
I have been using it for some time (2064 stored events) and I opted for streaming events by AccountUuid. In the projector_statuses table I have 1103 rows.

I only have one projector.

When I run php artisan event-projector:list I get this
![image](https://user-images.githubusercontent.com/1567162/52348556-4588d100-2a2d-11e9-907e-130a8f00b795.png)

I am thinking of rebuilding it to get everything back to normal (I'm guessing the above output means not everything is as it should be?)

The only thing the account balance projector does is update the accounts table with a balance and I have a resetState method in my account balance projector that truncates the accounts table.
So my questions are:
- Should it be ok to rebuild?
- Does reset only run the resetState method but not replay events?
- I've realised I never had an accountUuid property on all my events the projector received, do I need to update the rows in the stored_events table to include this property?
- I have event listeners that listen to the same events as my event projector so will rebuilding fire the actual event and resend notifications etc? 

Thanks for any help you can provide.
Roark

**Comment by freekmurze** [comment]
Closing this, as we won't support v1 in anymore. In v2 all functionality regarding projector statuses has been removed.
