### ISSUE TITLE
Recommendations for handling seed data?

### ISSUE THREAD

**Issue by alexciarlillo** [spatie/laravel-event-projector#122]
Was wondering if anyone has a good way of handling seed data? Should we just seed the stored events table and replay all the projectors? Or should we have individual seeders which actually call something like `createWithAttributes`? I'm sure there are pros and cons to each, but was just wondering if anyone else has run across this. Right now, just to get things moving, I am leaning towards simply seeding `stored_events` and replaying, but I have not found a good way to force the replay without user interaction.

**Comment by freekmurze** [comment]
In my example projects I let the seeders fire events and let the projectors populate the tables. But you could manually create records too. It's just a matter of preference.
