### ISSUE TITLE
Serialize and deserialize events with value objects

### ISSUE THREAD

**Issue by enricobono** [spatie/laravel-event-projector#126]
Hi.
I have this event:

```
class ReactionAdded implements ShouldBeStored
{
    private $Id;
    private $reactionType;

    public function __construct(
        int $id,
        ReactionType $reactionType
    ) {
    }
}
```

Well, I cannot projects the event, I get this error:
```
Failed to unserialize an event with class `App\Events\ReactionAdded` on stored event with id `11`. Are you sure that event class exists?
```

The stack trace shows `InvalidStoredEvent::couldNotUnserializeEvent`, and it seems it cannot deserialize the event, given I'm using the ´ReactionType` Value Object. 
What is the correct syntax to use an event with a value object in the constructor?

**Comment by freekmurze** [comment]
If the default serializer does not work for you, consider [creating your own custom one](https://docs.spatie.be/laravel-event-projector/v1/advanced-usage/using-your-own-event-serializer).
