### ISSUE TITLE
Sorting stored events by a field different than id

### ISSUE THREAD

**Issue by robertogallea** [spatie/laravel-event-projector#127]
I am migrating an application to event sourcing model. The application is backed by an oracle dbms. 

As far as I understood from projectors behavior and from the code, events are processed on the basis of their id. However, the tables in my application use a sequence cache. For this reason, newer events dispatched don't always have id greater of older ones, and projectors ignore them.

Do you thought about a different sorting strategy for events based, for example, on timestamp? 

If not, do you think it could be a good idea if I work on this feature and submit a pull request?

In the meanwhile I needed to disable sequence caching.

Anyway, great work!

**Comment by 36864** [comment]
The problem with using timestamps is that in high-concurrency situations, it's not difficult for two entries to be created with the same timestamp. Microseconds do mitigate this to a fair degree, but timestamps are still not guaranteed to be unique values.

I am not familiar with sequence caching, but from what I understand of your situation, this would only be a problem on the events table, correct? Can you disable sequence caching for only that table? 
If you can't, would there be situations in your app where an event that affects a model can have a lower ID than the event that creates the model? How big is your sequence cache / what is the longest period that a lower ID can be delayed?

**Comment by robertogallea** [comment]
Yes it is correct, it would be a problem only on events table.

Yes, I can disable sequence caching, and this is what I have currently done, but I have to give up the consequent performance benefits.

Yes model creation could be preceded by another event related to the same model (in terms of generated sequence ids), I will try described how I noticed the problem (my cache size is 20):

1. **CreatedEvent: id 21**: Model is created, <code>last_processed_event_id = 21</code>
2. **UpdateEvent: id 41**: Model is updated, <code>last_processed_event_id = 41</code>
3. **UpdateEvent: id _22_**: Model is _not_ updated_, because Projector believes it is antecedent the last processed event.

Note that the same problem occur when replaying events, because for sure the events would be processed in wrong order, this could lead to wrong projections or even errors (for example, attempts to update a model which was already deleted)

My sequence cache is currently 20, but it could be adjusted according to requirements, also, I don't know neither the longest period that a lower ID can be delayed, nor the logic used by Oracle for using the cached ids or generating another batch.


In the end, probably ordering is just the wrong purpose for a sequence, so I have to keep cache disabled or rely on very fine-grained timestamps. Do you agree?

**Comment by 36864** [comment]
Yes, I understand your issue better now.

If your models are unlikely to be edited by many people (say, blog post that are usually edited by one person), then using timestamps could be a workable solution.

Otherwise, I think disabling the sequence cache is your best option.
