### ISSUE TITLE
Add methods to disable projector(s)/reactors(s)

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#131]
Something like `Projectionist::withoutReactor(MyReactor::class)`.

This could be useful for integration tests.

**Comment by adrianb93** [comment]
This is very helpful. I want to add a PR to add this to the docs, but not sure where it would belong given it covers projectors and reactors.

Would you accept a PR for the following?:

* `Projectionist@withoutReactor`
* `Projectionist@withoutReactors`
* `Projectionist@withoutProjector`
* `Projectionist@withoutProjectors`

If these exist, I can add them to the docs in the configuring projectors/reactors sections.

**Comment by freekmurze** [comment]
@adrianb93 Let's keep it simple and only add one method: Projectionist@withoutEventHandlers. It can accept a class name of an event handler (= a projector or a reactor) or an array of classnames.

Make sure to add a test for this too 👍
