### ISSUE TITLE
Consider reworking events

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#132]
- Call them `DomainEvent` instead of `ShouldBeStored`
- Use our DTO package, would reduce complexity with (de)serialization

**Comment by freekmurze** [comment]
- renamed it to `DomainEvent` for now, but unsure if we should keep this. Not everybody uses `Domain` like we do
- the current deserialisation seems to work fine. Did you encounter any specific problems with it?
