### ISSUE TITLE
A general question for event sourcing in production

### ISSUE THREAD

**Issue by guitarbien** [spatie/laravel-event-projector#134]
Hi, Thanks the package, it let me better understand the event sourcing. But I still have some general questions :

In the demo app,  we enqueue the attributes in the `Account` model to create an account. I don't understand why the creation was happened in the projector? If an account is not `save()` to the database then there should not an event `AccountCreated` I think.
And if we really use a queue service like rabbitmq or aws sqs, we wouldn't know whether the messages (events) are processed or not, so query the attributes in the account table could fail then.

Thanks.

```php
    /**
     * @param array $attributes
     * @return Account
     * @throws \Exception
     */
    public static function createWithAttributes(array $attributes): Account
    {
        /*
         * Let's generate a uuid.
         */
        $attributes['uuid'] = (string) Uuid::uuid4();

        /*
         * The account will be created inside this event using the generated uuid.
         */
        event(new AccountCreated($attributes));

        /*
         * The uuid will be used the retrieve the created account.
         */
        return static::uuid($attributes['uuid']);
    }
```

**Comment by nokios** [comment]
In event sourcing, the event is the source of truth, not the eloquent model that represents the current state.

This is where you're confused. The event is recorded first, the eloquent model is created after, and modified after any future event.
