### ISSUE TITLE
Cannot Extend EventProjectorServiceProvider

### ISSUE THREAD

**Issue by adrianb93** [spatie/laravel-event-projector#140]
**Issue:**

I cannot upgrade to v2 because the `EventProjectorServiceProvider` is marked as `final`.

**Why it was extended:**

I have a multitenant application running on Laravel Event Projector. I extend the service provider to set a `PreEventSubscriber` and `PostEventSubscriber`.

```php
...
use Spatie\EventProjector\EventProjectorServiceProvider as ServiceProvider;

class EventProjectorServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Event::subscribe(PreEventSubscriber::class);

        parent::boot();

        Event::subscribe(PostEventSubscriber::class);
    }
}
```

My `PreEventSubscriber` figures out what `StoredEvent`/`TenantStoredEvent` model to use:

```php
public function handle(string $eventName, $payload)
{
    if (! $this->shouldBeStored($eventName)) {
        return;
    }

    if (! $this->isTenantEvent($eventName)) {
        return;
    }

    config()->set('event-projector.stored_event_model', TenantStoredEvent::class);
}
```

... and my `PostEventSubscriber` sets the `StoredEvent` model back to the default:

```php
public function handle($event)
{
    config()->set('event-projector.stored_event_model', StoredEvent::class);
}
```

**Questions:**

I need those pre and post checks to use this package in my setup. Any chance you:

* could reconsider making the class `final`?
* know of another way I could accomplish this?
* could let me know what you'd be willing to accept as a PR to improve extendability in regards to your intentions behind making classes final?

**Comment by freekmurze** [comment]
I've removed `final`. Enjoy your newfound freedom.

**Comment by adrianb93** [comment]
Thank you. I'm not used to working with final classes. The `boot` and `register` methods are in the public API for service providers though. I can do this instead:

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Illuminate\Support\ServiceProvider;
use App\Listeners\EventProjector\PreEventSubscriber;
use App\Listeners\EventProjector\PostEventSubscriber;
use Spatie\EventProjector\EventProjectorServiceProvider as PackageServiceProvider;

class EventProjectorServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Event::subscribe(PreEventSubscriber::class);

        tap(new PackageServiceProvider($this->app), function ($provider) {
            $provider->boot();
        });

        Event::subscribe(PostEventSubscriber::class);
    }

    public function register()
    {
        tap(new PackageServiceProvider($this->app), function ($provider) {
            $provider->register();
        });
    }
}
```

Although I don't think much damage can be done from extending this packages service provider, you can keep it final if you wanted to.
