### ISSUE TITLE
Consider unifying projectors and reactors

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#141]
The two classes are essentially the same with one key difference: reactors aren't run during replays.

We could unify them as "consumers" or something similar, and add a `Replayable` interface to hint whether they need to be run once or twice.

If we decide to keep things as is (which might be a better idea because separating the two makes it easier to explain to beginners), I think we could do some internal refactors to unify the two and reduce the amount of code in this package.

**Comment by freekmurze** [comment]
I'm thinking of keeping these names and not go for a generic `Consumer`. Like you said, keeping the current names is easier for newcomers to grasp the concepts.

> I think we could do some internal refactors to unify the two and reduce the amount of code in this package.

I'll already take a look. Feel free to PR stuff.
