### ISSUE TITLE
Reduce configuration with magic

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#143]
Some of the mapping that needs to be done can be quit tedious, and I think we could reduce the amount of configuration necessary with reflection.

1) `$handlesEvents` could be infered by scanning a projector/reactor, and checking the public method typehints. If something with a `ShouldBeStored` interface is hinted, we know which event it applies to.

2) Autodiscover your applications projectors and reactors based on `Projector` and `Reactor` suffixes

If we introduce some sort of auto configuration, some sort of `php artisan event-projector:inspect` could be useful to see the config (similar to `routes:list`).

It also might be a good idea to start caching things so we don't need to do reflection on every request.

Note: all of this behaviour should be opt-in and overridable per event handler!

**Comment by freekmurze** [comment]
Magic has arrived!
