### ISSUE TITLE
Create new storable event by artisan command doesn't run

### ISSUE THREAD

**Issue by kufdaw** [spatie/laravel-event-projector#144]
Wanted to create new storable event, as it is said in docs, by `php artisan make:storable-event NameOfYourEvent` but after that I receive the error: `Command "make:storable-event" is not defined. `

What is worth to notice: I could easily create the projector using artisan.

**Comment by hussartech** [comment]
https://github.com/spatie/laravel-event-projector/blob/master/src/Console/MakeStorableEventCommand.php

try: 
`make:domain-event`

**Comment by kufdaw** [comment]
Yeah, it works, thanks, it seems docs is outdated.

**Comment by kufdaw** [comment]
> https://github.com/spatie/laravel-event-projector/blob/master/src/Console/MakeStorableEventCommand.php
> 
> try:
> `make:domain-event`

Yeah, it works, thanks, it seems docs is outdated.

**Comment by kufdaw** [comment]
Additionally I noticed that this command uses boilerplate like this: 
```
<?php

namespace App\StorableEvents;

use Spatie\EventProjector\DomainEvent;

final class TaskMadeInProgress implements ShouldBeStored
{
    public function __construct()
    {
    }
}
```

so it imports DomainEvent instead of ShouldBeStores class.

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention.

I've just tagged a new release that fixes this.
