### ISSUE TITLE
General questions about projector and the app state in event sourcing system

### ISSUE THREAD

**Issue by guitarbien** [spatie/laravel-event-projector#145]
Hi, first of all, I like the v2 docs. The **Getting familiar with event sourcing** part helps a lot for me.

I am still learning DDD & event sourcing, my first question is:
Base on the [aggregate example](https://docs.spatie.be/laravel-event-projector/v2/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past), we use an `accounts` table to recording the account balance. But we have all events already and can `reconstituteFromEvents()` to the aggregate, so we know the **balance** number actually, can we just use the aggregate ? Or the `accounts` table is a kind of **snapshot** in the event sourcing system ?

The other question is about projector. If two projectors want to handle one event, how will they execute in sequence ? Follow the items of `projectors` array ?

Thanks.

**Comment by freekmurze** [comment]
> Hi, first of all, I like the v2 docs. The Getting familiar with event sourcing part helps a lot for me.

Great to read this is useful for you! 👍 

> Base on the aggregate example, we use an accounts table to recording the account balance. But we have all events already and can reconstituteFromEvents() to the aggregate, so we know the balance number actually, can we just use the aggregate ? Or the accounts table is a kind of snapshot in the event sourcing system ?

Great question, I had the same question too when learning all this. 

The only function of the aggregate is to decide which events should get written. It should not try to write any other state itself, nor should other parts of your system depend on the internal state of the aggregate.

So, the aggregates is responsible for deciding if the balance may change. If other parts of your system are interested in the actual balance, create a projection that persist the balance and query that.

> The other question is about projector. If two projectors want to handle one event, how will they execute in sequence ? Follow the items of projectors array ?
I think so.
