### ISSUE TITLE
assuring priority to store the event?

### ISSUE THREAD

**Issue by Grummfy** [spatie/laravel-event-projector#15]
Hello,
the package seems interesting and nice idea are present but one thing in event sourcing is very important : being sure to be able to reread the event, so be sure it is stored. So for me it's important that storing the event is coming as a first step before anything else.

Why?
Because if you can\'t store the event, the event shouldn't be dispatched. Otherwise you risk some incoherence in case of replaying. So for me, if this case is not solved you risk very bad stuff.
So the issue is not something that could happens in all case (imagine that you can save an account that have been changed by an event but not the event itself) but it's something that should be considered or at least have a warning about it.

As I have seen a lot of people using a tech to dispatch the event that store it for them (so dispatching the event = storing it) that solve this particular issue by itself.

A possible solution would be, not to have a priority system (laravel remove it and reading it is not a so nice solution (I have done it on my project)) but simply log the event to be able to restore it by some manual operation.

thanks for reading

**Comment by freekmurze** [comment]
Validation of commands / events is out of scope of this package. This is a responsability of the user of the package. I'll be sure to mention that in the docs.

Events can be easily restored like this:

```php
StoredEvent::find($id)->event // returns the actual event;
```

I you see some simple, easy wins in the package, I'm open for suggestions and PRs.

Closing this for now, but feel free to continue the conversation.
