### ISSUE TITLE
Upgrading an app that was using event streams?

### ISSUE THREAD

**Issue by alexciarlillo** [spatie/laravel-event-projector#156]
If you had an app in production that was using event streams, from version 1.3 and want to migrate to v2 of the package, what steps would you need to take if any?

**Comment by freekmurze** [comment]
Streams aren't supported anymore, in v2 you yourself are responsible for tracking which events already have been passed to event handlers when replaying events.

Upgrade instructions: https://github.com/spatie/laravel-event-projector/blob/master/UPGRADING.md#from-v1-to-v2
