### ISSUE TITLE
replay command does not support --force flag

### ISSUE THREAD

**Issue by radmen** [spatie/laravel-event-projector#157]
When running `event-projector:replay --force` command still asks for confirmation.

![Screenshot from 2019-04-25 14-00-01](https://user-images.githubusercontent.com/1190255/56734188-7510c500-6762-11e9-909e-f16fa09bce23.png)

Package version: `1.3.1`
Laravel version: `5.7`

**Comment by freekmurze** [comment]
We don't support v1 anymore. Please upgrade to v2.

**Comment by radmen** [comment]
Oh. Wow... Totally missed that. Thank you!
