### ISSUE TITLE
Changing projectors / reactors dependency implementations during tests

### ISSUE THREAD

**Issue by talvbansal** [spatie/laravel-event-projector#158]
Hey,

First I love the package its been a fantastic way of getting into event sourcing for a project my team has been working on.

In this project we have a reactor that makes calls out to a third party. I want to be able to swap the implementation during testing which is something I've typically done using something like the following previously in our tests.

```php
$this->app->singleton(FakeThirdPartyInterface::class, function () {
	return new FakeThirdPartyImplementation();      
});
```
Since the projectors / reactors are registered and created in the apps service provider / `EventProjectorServiceProvider` trying to swap the implementation out at the start of my test method is too late in the request lifecycle and so the swap doesn't work.

Are there any ways to get around this that I'm not seeing?

**Comment by sebastiandedeyne** [comment]
Maybe we should register event handlers after the app is booted @freekmurze?

**Comment by freekmurze** [comment]
I'd accept a PR that moved the registration to the `boot` method.

**Comment by talvbansal** [comment]
@sebastiandedeyne I've just tried moving this code 

```php
$this->app->singleton(Projectionist::class, function () {
            $config = config('event-projector');

            $projectionist = new Projectionist($config);

            $projectionist
                ->addProjectors($config['projectors'] ?? [])
                ->addReactors($config['reactors'] ?? []);

            return $projectionist;
        });
```

from the register to the boot method, but theres no change in the functionality. I assume by the time we're at the first line of a test method the app has finished registered and booted even if the test is blank. 

I can't think of an obvious way to hook into the app lifecycle to swap Fakes in during tests unless I'm missing something obvious. If there is something please point me in the right direction and ill take another look.

As a work around for now I'm doing the following. Swapping the implementation, fetching the Projectionist from the app container and overwriting the reactor's key held within the EventHandlerCollection.

```php
        $this->app->singleton(ClaimsManagementNotifier::class, function () use ($fakeRequests) {
            $mock = new MockHandler($fakeRequests);

            $handler = HandlerStack::create($mock);
            $client = new \GuzzleHttp\Client(['handler' => $handler]);

            return new ClaimsManagementNotifier($client);
        });

        /** @var Projectionist $projectionist */
        $projectionist = $this->app->make(Projectionist::class);
        $projectionist->addReactor(AppClaimReactor::class);
```
