### ISSUE TITLE
Replay events when AggregateRoot::$storedEventModel used

### ISSUE THREAD

**Issue by mfullbrook** [spatie/laravel-event-projector#162]
I've noticed that the ReplayCommand only uses the `event-projector.stored_event_model` configuration value. 

The addition of `$storedEventModel` on `AggregateRoot` allows us to use different event storage models per AggregateRoot 👍  But currently we are not be able to replay the events from a non-default event store.

Happy to work on a PR.  To me the most sensible modification would be an optional `--store=` option.  What do you think?

**Comment by freekmurze** [comment]
That option sounds good to me, I’d welcome a PR
