### ISSUE TITLE
get the uuid in reactor

### ISSUE THREAD

**Issue by guitarbien** [spatie/laravel-event-projector#166]
Hi, I follow the doc [Getting the uuid of an event](https://docs.spatie.be/laravel-event-projector/v2/using-reactors/creating-and-configuring-reactors#getting-the-uuid-of-an-event)，want to get the `aggregate_uuid`, but get the whole stored event data row in a json format
```json
{
  "id": 10,
  "aggregate_uuid": "29abf3d9-c4ba-4a77-a2dd-f77f929dd4df",
  "event_class": "App\\Events\\OrderDelivered",
  "event_properties": {
    "deliveredAt": "2019-05-30 15:00:00"
  },
  "meta_data": [],
  "created_at": "2019-05-30 17:02:08"
}
```
Is the doc out of date ?
Thanks.

**Comment by guitarbien** [comment]
And the `rebuild` artisan command seemed not exists ?

**Comment by freekmurze** [comment]
I've update the docs, you should use `$aggregateUuid` as the variable name instead of `$uuid`.

**Comment by freekmurze** [comment]
> And the rebuild artisan command seemed not exists ?

It was removed in `v2`. please use `replay`  instead.

If you encounter more problems, please open up separate issues for each. If you spot an error in our docs, you could click the `edit` button present on the top of each page, to easily create a PR.
