### ISSUE TITLE
Projector priority when replaying

### ISSUE THREAD

**Issue by rodrigopedra** [spatie/laravel-event-projector#175]
Is there a way one can define an order Projectors `resetState` methods should be executed while replaying?

I have foreign keys enabled, so for my app it is important that the `resetState` is executed in a particular order.

I tried registering the projectors manually in the config file, but as they are registered by their class names as a key, it didn't work.

I have some suggestions to approach this issue:

1. In the `Projectionist@replay` method, we can move the `StartingEventReplay` event dispatch before the for-loop which reset all the states [see code](https://github.com/spatie/laravel-event-projector/blob/master/src/Projectionist.php#L259-L267), this way one could disable foreign keys before on this event and re-enable on the `FinishedEventReplay` event.

2. Add two new events (`StartingStateReset` and `FinishedStateReset`) around that same for-loop to a similar approach. This would not be a breaking change as it is an added functionality.

3. Allow projectors to have a `$priority` property and sort the `$projectors` collection accordingly before replaying the events.

If this is something that can be accepted I am glad to send a PR.

Thanks for the grate package!

UPDATE: In my opinion, option n.2 is the better option. Of course you might find an even better approach

**Comment by freekmurze** [comment]
I'm ok with option 2. Send a PR with tests for this. 👍

**Comment by rodrigopedra** [comment]
Missed your reply notification, will send later this week, thanks.
