### ISSUE TITLE
Support for ephemeral events

### ISSUE THREAD

**Issue by Jnesselr** [spatie/laravel-event-projector#181]
I'm pretty sure this isn't supported yet, but I figured I'd ask. Is there any support/plan to support ephemeral events? Specifically, I'm referring to events where it's okay if a handler only process the last event in the series.

The reason I ask is that I have a system where there's a progress update that needs to get reported. Right now, outside of an event sourced system, I'm just updating the model itself. Inside an event sourced system, it appears I would need to use an event for this. However, the percentage is updated in 0.01% increments so that's potentially 10,000 events per job for no particular reason.

Thoughts on either how to handle this without ephemeral events or ideas on how to implement them in the framework? I don't think keeping every event in there is a good idea, not because I think MySQL can't handle it, but because going through those events in Aggregate is going to be way slower for not much benefit.

**Comment by Jnesselr** [comment]
Looking at the code itself, it seems like a way (not sure if it's the best way yet) would be to add support for another job that handles cleaning up the older ephemeral events every time a new event is persisted, assuming that domain event implemented some interface for the ephemeral events.

In my case, I'd only need ephemeral support for a particular UUID, meaning I could handle it by just saying "any event of this type that is older based on the created at timestamp can be deleted". I don't know how that works if a projector/aggregate/reactor is handling the event I just deleted. In my case, I wouldn't care because a newer event would exist. I'd like to think that's true of all ephemeral events, but I'm not 100% sure that's true.

I guess I could also define something like an aggregate (let's call it an ephemeral manager?) that could respond to any events, not just something with an "ephemeral" interface. This manager would have the ability to process through the events like an aggregate, but would also have the ability to delete events. Granted, that might also be too much power for the class, because then they could delete any event they wanted, not just the ephemeral class.

**Comment by freekmurze** [comment]
Right now I have no need for ephemeral events, so probably I'm not investing time to add support for this. A pragmatic, maybe naive, solution would be to solve it before you call the aggregate. You could throttle events before calling the aggregate.

**Comment by Jnesselr** [comment]
Just to clarify your objectives for this library, is it only what you would use, or is it what other's might use as well? Because I wouldn't want to "reinvent the wheel" just to get some piece of functionality (although there could be other requests in the future, so maybe I should just reinvent it), but I also totally understand if it's not your goal to support anything beyond your own use case. I'm assuming if I make the code and submit a pull request, that's okay?

**Comment by freekmurze** [comment]
Feel free to whip up a PR. If the code to achieve this is simple, easy to maintain and has tests, I’ll consider merging it. 👍
