### ISSUE TITLE
Example in the documentation not working

### ISSUE THREAD

**Issue by jupiron** [spatie/laravel-event-projector#26]
Hi,

I was trying to test your package running the example from the documentation, but I cannot manage to do so. I created the model, the events and the projector strictly following the [doc](https://docs.spatie.be/laravel-event-projector/v1/basic-usage/writing-your-first-projector), but when I run `$account = App\Account::createWithAttributes(['name' => 'Julien']);`, `$account` is equal to null.

Am I doing something wrong or is the example erroneous?

**Comment by DigicreateJens** [comment]
I think they meant `$account = App\Account::**create**(['name' => 'Julien']);` instead of `createWithAttributes`.

**Comment by freekmurze** [comment]
I'll fix the docs soon. For now you can do what @DigicreateJens suggested.
