### ISSUE TITLE
Slight event handling declaration improvement...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-event-projector#35]
Hi,

I'd like to make what I consider a slight improvement to the event handling declaration for a projector.

From the documentation (https://docs.spatie.be/laravel-event-projector/v1/basic-usage/writing-your-first-projector#creating-your-first-projector):

```
    /*
     * Here you can specify which event should trigger which method.
     */
    protected $handlesEvents = [
        AccountCreated::class => 'onAccountCreated',
        MoneyAdded::class => 'onMoneyAdded',
        MoneySubtracted::class => 'onMoneySubtracted',
        AccountDeleted::class => 'onAccountDeleted',
    ];
```

I would like to allow for the following:

```
    /*
     * Here you can specify which event should trigger which method.
     */
    protected $handlesEvents = [
        AccountCreated::class,
        MoneyAdded::class,
        MoneySubtracted::class,
        AccountDeleted::class,
    ];
```

To me, this seems a bit easier/nicer and less error-prone.  That is, instead of writing handler method name in **two** places, one must only enter it once.  I know it's minor, but it seems like an improvement.

So, my thought is that when the array is in this structure, then it will automatically look for `on{$eventName}` methods.

**I've just forked the project and am happy to find and submit a solution, but I'd first like to hear back to find out if it's time worth spending.**

Thx....

**Comment by freekmurze** [comment]
Good idea, feel free to submit a PR, be sure to include tests to make sure that it works. Also send a PR to the docs.

Your work is much appreciated!

Closing this for now, but if you have more questions, feel free to add a new comment.

**Comment by jpnut** [comment]
I'm a fan of this idea. If this does get implemented, might it make more sense to flip the `$handlesEvents` key - values? i.e. `'onAccountCreated' => AccountCreated::class`, that way you can support both ways and don't need to worry about the class name being either the key or the value.

**Comment by telkins** [comment]
@jpnut 

Thx.

Regarding flipping `$handlesEvents`...I have mixed feelings,  to be honest.  I think it will make implementing it a bit easier, but I'm stuck on the way it would read.  To me, it makes most sense that the event **leads to** the method being called.  The arrow (`=>`) fits this mental image perfectly for me.  Flipping them means that it's not as intuitive **for me**.  Does that make sense?

Whatever the case, I would happily do it, but would prefer some additional discussion and/or input form the package owners to see if they have any preferences.  @freekmurze ...?

**Comment by freekmurze** [comment]
I'm not a fan of flipping the keys. Its more natural if we keep the order:
If `AccountCreated::class` then `onAccountCreated`

**Comment by telkins** [comment]
@jpnut Sorry, my friend, but "The Master" has spoken.  ;-)

**Comment by jpnut** [comment]
Haha of course! You make a convincing argument, and I have to agree that readability takes precedence over what is easiest to code.
