### ISSUE TITLE
RebuildCommand doesn't work if projector list is ommited

### ISSUE THREAD

**Issue by 36864** [spatie/laravel-event-projector#42]
`EventProjectionist::getProjectors()` returns a collection of strings, while `EventProjectionist::getProjector()` instantiates a projector before returning it. This causes RebuildCommand to attempt to call `reset()` on strings, rather than projector instances, due to the way the `SelectsProjectors` trait fetches projectors when the projector list is ommited.

There are three ways to fix this:
- Change `EventProjectionist::getProjectors()` to return Projector instances;
- Change `SelectsProjectors` to assign `$projectorClassNames = EventProjectionist::getProjectors()` instead of the early return;
- Change `RebuildCommand` to check if the projectors have been instantiated before attempting to call `reset()` on them.

The first option would probably be best, possibly with the addition of a new `getProjectorNames` method to let developers check what projectors have been registered without having to instantiate them.

**Comment by freekmurze** [comment]
Thank you reporting this. I've implemented the first option. I'll add `getProjectorNames` when people will ask for it. Yagni.
