### ISSUE TITLE
Plans to support async event processing?

### ISSUE THREAD

**Issue by Harrisonbro** [spatie/laravel-event-projector#48]
First, thanks for building this! Looks like it will be a great help.

Do you have any plans to support async event processing rather than how the package (I presume) works currently where events are processed during the same request as an event is created?

More generally, do you think there is a benefit to async event processing? Could it make an event-sourced application more robust?

**Comment by 36864** [comment]
You can queue events for async processing: https://docs.spatie.be/laravel-event-projector/v1/basic-usage/making-sure-events-get-handled-in-the-right-order#handling-events-in-a-queue

As for the benefits of async processing, the second paragraph of the section I linked answers it. If you're gonna need the result of the event's processing in the same request as the event is generated, use sync events. Else, async away.

**Comment by Harrisonbro** [comment]
Great, thanks.

Presumably when you say _“you can set the name of the queue connection 
in the `queue` key of the `event-projector` config file”_ you’re 
referring to the same queue connections defined in the applications 
Laravel configuration?

**Comment by Harrisonbro** [comment]
Great, thanks.

Presumably when you say...

> _"you can set the name of the queue connection
in the `queue` key of the `event-projector` config file"_ 

...you’re referring to the same queue connections defined in the application's Laravel configuration?

**Comment by 36864** [comment]
Yes, naturally. It might be worth noting that you can set this per Projector, meaning the same event can be handled synchronously by some projectors, and asynchronously by others, and even in different queues.
For example, if you emit a "TaskCreated" event, you might want to immediately update your `tasks` table, but queue the update to your metrics reports.
