### ISSUE TITLE
Add --force flags to commands

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-projector#52]
In dev, `event-projector:rebuild` will be used a lot, annoying that you always need to pass the confirmation now.

**Comment by 36864** [comment]
In this regard I'd like to see the `--no-interaction` flag to be treated as a force flag. Doesn't really make much sense that running the command with a no interaction flag has no effect.

**Comment by sebastiandedeyne** [comment]
Maybe both is the way to go, to be the same as Laravel's commands. For example, from `php artisan help migrate`:

```
    --force                Force the operation to run when in production.
-n, --no-interaction       Do not ask any interactive question
```

**Comment by 36864** [comment]
They seem to serve different purposes. A `--no-interaction` may still fail to run if the app is in production, while `--force` may still require some user input, but won't refuse to run in production.
