### ISSUE TITLE
Going 'back in time' 

### ISSUE THREAD

**Issue by sunscreem** [spatie/laravel-event-projector#62]
Just getting my head around this package, its great!

Is it easy enough to recreate a state at a certain point in time? Eg using the bank example is there a simple way to show an account balance on xxx date?

**Comment by 36864** [comment]
The way I solved this for my simple task list app was to make a new "HistoryProjector" which will only process events up to a certain point. It's not perfect, but it works for what I wanted it to do: https://github.com/36864/Event-Sourced-Task-Lists/blob/master/app/Projectors/HistoryProjector.php

Earlier I had made a PR here to pass an upper limit to ReplayEvents, but issues surfaced regarding user interaction with an application in "history" mode.

**Comment by sunscreem** [comment]
Cool - I'll have a play with that approach.

Thank you.
