### ISSUE TITLE
setCircularReferenceLimit

### ISSUE THREAD

**Issue by codesmith55** [spatie/laravel-event-projector#64]
I have the setup as the code snippets below and I'm getting a tricky to google "A circular reference has been detected when serializing the object of class "Illuminate\Database\MySqlConnection" (configured limit: 1)".

Create a Unit. When the unit is actually created in UnitCreated I want to create a random number of Augments, and then assign those augments to the unit, instantiating AugmentAdded events. 

Is this broken or am I using the wrong pattern?

Unit.php:

public static function createWithAttributes(array $attributes): Unit
{

    $attributes['uuid'] = (string) Uuid::uuid4();

    /*
     * The Unit will be created inside this event using the generated uuid.
     */
    event(new UnitCreated($attributes));

    /*
     * The uuid will be used the retrieve the created Unit.
     */
    return static::uuid($attributes['uuid']);
}

public function addAugment(Augment $augment)
{

    event(new AugmentAdded($this->uuid, $augment));
}  
UnitProjector.php:  

public function onUnitCreated(UnitCreated $event)
{
    $unitCreated = Unit::create($event->unitAttributes);
}

public function onAugmentAdded(AugmentAdded $event)
{
    $unit = Unit::uuid($event->unitUuid);
    $unit->augments()->attach($augment->id);
    $unit->save();
}
class AugmentAdded implements ShouldBeStored {

/** @var string */
public $unitUuid;

/** @var augment */
public $augment;

public function __construct(string $unitUuid, Augment $augment)
{
    $this->unitUuid = $unitUuid;
    $this->augment = $augment;
}
}

**Comment by freekmurze** [comment]
Try to avoid using objects that cannot be serialized as public properties on events.

Alternatively you could write your own serializer: https://docs.spatie.be/laravel-event-projector/v1/advanced-usage/using-your-own-event-serializer

**Comment by codesmith55** [comment]
Great. I found a way around it but that'll do fine. I can assign an ID or something if I really needed to. Cheers.
