### ISSUE TITLE
environment variable EVENT_PROJECTOR_QUEUE_DRIVER is confusing

### ISSUE THREAD

**Issue by jovanialferez** [spatie/laravel-event-projector#66]
https://github.com/spatie/laravel-event-projector/blob/f11896f4b50d8aafd1c5471eea239bffde844229/config/event-projector.php#L28

the name `EVENT_PROJECTOR_QUEUE_DRIVER` is pretty confusing when it actually is used as the queue name, not the driver nor the connection.

**Comment by freekmurze** [comment]
You're right, I'd accept a PR that fixes this.
