### ISSUE TITLE
What's the point of having timestamps in projected models?

### ISSUE THREAD

**Issue by DiederikvandenB** [spatie/laravel-event-projector#68]
Hi! Thanks for your amazing open source work, a postcard will be on the way soon ;).

I had a question regarding models that have entries that are created through a projector. In [the docs](https://docs.spatie.be/laravel-event-projector/v1/basic-usage/writing-your-first-projector#creating-a-model), the migration comes with `$table->timestamps();`. I was wondering if these fields are still useful. If you do a `php artisan event-projector:rebuild`, these fields will contain the date and time of when the artisan command was run.

In our current setup, I dropped the timestamps from the mutation. My colleague however pointed out that it would be nice to have insights in when the entries were rebuild. Therefore, it would make sense to drop the `updated_at` field and rename the `created_at` in to `projected_at` or something.

Another solution would be to extrapolate the created_at and updated_at from the events. This would be the cleanest solution as the value of the date fields would make sense, but it is probably much harder to achieve.

**Comment by freekmurze** [comment]
> Another solution would be to extrapolate the created_at and updated_at from the events. This would be the cleanest solution as the value of the date fields would make sense, but it is probably much harder to achieve.

That would indeed be the best solution.

I left the `timestamps` there just to stay as close to a default Laravel model/migration as possible.

**Comment by DiederikvandenB** [comment]
Would you be interested in a PR for this btw? Not sure if I find the time for it, but I'll do my best.

**Comment by freekmurze** [comment]
@DiederikvandenB sure. No pressure, take your time.
