### ISSUE TITLE
Fake event projecting when testing

### ISSUE THREAD

**Issue by hxnk** [spatie/laravel-event-projector#74]
First: I love this package! I'm currently implementing it in a project I'm working on and it's worked great so far!

It would be nice to be able to "fake" event projecting when running tests, preventing all projectors and reactors from executing by default, and allow only specific Projectors/Reactors to actually handle events.

We could then run assertions on the outcome of the projectors/reactors that did execute (and we actually care about for the given test). For those that did not execute (and were faked) we can assert that they would have been triggered by a given event.

If I were to implement this (and submit a PR 😉), I would probably go for an api like this:

```php
// Start faking the event projecting and allow running given projector(s) and/or reactor(s).
Projectionist::fake($allowedHandlers);

// Allow faked projectionist to run given projector(s) and/or reactor(s).
Projectionist::allowHandler($allowedHandlers);

// Allow faked projectionist to run all sync projectors.
Projectionist::runAllSyncProjectors();

// Assert that a disabled projector or reactor would have been called with given event.
Projectionist::assertCalledWith($eventHandler, $event);

// Assert that a disabled projector or reactor would not have been called with given event.
Projectionist::assertNotCalledWith($eventHandler, $event);
```

Let me know what you think!

**Comment by freekmurze** [comment]
Go ahead and submit a PR for this! 👍
