### ISSUE TITLE
Set metadata when event is emitted

### ISSUE THREAD

**Issue by 36864** [spatie/laravel-event-projector#75]
Currently, there is no way to add metadata to an event when you emit it. Instead, you have to either hook into the model's creating events or manipulate it after it's been saved to the database.
I think it should be possible to add metadata to an event when it is generated. Here's my concrete use case for this:

I'm working on an "Undo" feature which undoes the last event generated by the user by emitting the opposite event (Created <=> Deleted). Of course if I just fetch the last event, clicking undo twice will constantly create/delete the same model. 

To get around that, I would like to add some metadata to an event which marks it as an "undo" action. Then I'd only need to fetch the latest event that isn't an undo action and that hasn't been undone (marking an event as "undone" is easy enough with the current system).

I believe a projector shouldn't have to know whether the event it's handling is undoing an earlier event or not. As far as it's concerned, a create event makes a model and a delete event deletes a model.

To solve this, I propose allowing events to define a `public $meta_data` property that would be used in the StoredEvent constructor. An example usage in an event would look something like this:

```php
class TaskCreated implements ShouldBeStored
{
    use Dispatchable, Undoable;

    /** @var array */
    public $meta_data

    /** @var array */
    public $taskAttributes;

    /** @var string */
    public $undoEvent = TaskDeleted::class;

    /** @var array */
    public $undoAttributes = ['taskAttributes'];

    /**
     * Create a new event instance.
     *
     * @param array $taskAttributes
     * @return void
     */
    public function __construct(array $taskAttributes, array $meta_data = [])
    {
        $this->taskAttributes = $taskAttributes;
        $this->metadata = $meta_data;
    }
}
```

This would allow me to simply pass an additional parameter to an event to set metadata instead of having to pollute its event_properties with some kind of marker that doesn't directly relate to the event. An undo routine could look something like this:
```php
public function undo()
{
    $event = StoredEvent::whereNull('meta_data->undo') // Ignore Undo Events
      ->whereNull('meta_data->undone') // Ignore Undone Events
      ->latest()
      ->firstOrFail()
      ->getEventAttribute();

    if (method_exists($event, 'undo')) { // Check if event is undoable
      $event->undo();
    }
    else {
      throw new \Exception("This action cannot be undone.", 1);
    }
}
```

I considered just making a PR for this, but I thought I'd explain my use case first and see if this all makes sense or if there's some other way I should be doing this, or if I've missed an obvious way to set metadata on event creation.

**Comment by sebastiandedeyne** [comment]
Imo, "undo" should be an event in itself in this case, or do you think that's overengineered?

Beyond that matter, I think a way to add meta data when creating an event somehow would be useful either way!

**Comment by freekmurze** [comment]
> Imo, "undo" should be an event in itself in this case, or do you think that's overengineered?

Agreeing with @sebastiandedeyne here

>  I think a way to add meta data when creating an event somehow would be useful either way!

You can to this with model events. I've added an example to #79
