### ISSUE TITLE
In-memory event replay

### ISSUE THREAD

**Issue by pmartelletti** [spatie/laravel-event-projector#76]
Hey @freekmurze - are you guys planning to support in-memory replay of the events for a given projector?

The idea is to have a projector that will take all the events for a given uuid, and it only replays those?

With this, you can versioning (or the state at a certain point in time) quite easily.

Thanks.

**Comment by pmartelletti** [comment]
@freekmurze I'm talking about something like this (as I feel I was not very clear):

http://verraes.net/2014/03/practical-event-sourcing/

Being able to retrieve the current state of a model based on the stored events.

**Comment by sunscreem** [comment]
This sounds similar to my question on #62.

Being able to quickly reply events in memory would be great?

**Comment by pmartelletti** [comment]
Yeah, I'd be nice if there's something out of the box to retrieve all the events for a given event type and a uuid. But if there's not, I don't think it would be really hard to build one myself. Just wondering if it was in the plans or this project is just for projections.

**Comment by sebastiandedeyne** [comment]
What do you mean by "in-memory" exactly?

I think it would make sense to be able to pass a date to `event-projector:rebuild` to only apply events until that specific date.

**Comment by pmartelletti** [comment]
@sebastiandedeyne well, I mean being able to rebuild the state of an entity based on the events it has recorded, and not only by projections. Example:

```php
public static function reconstituteFrom(AggregateHistory $aggregateHistory)
    {
        $cashflowId = $aggregateHistory->getAggregateId();
        $cashflow = new Cashflow(CashflowId::fromString($cashflowId));

        foreach($aggregateHistory as $event) {
            $cashflow->when($event);
            $cashflow->recordedEvents[] = $event;
        }

        return $cashflow;
    }
```

In this case, you'll pass all the events for this Aggregate as param, and then rebuild the current state for the model based on those events. If you just want to check what was the state yesterday, you'll pass the events till yesterday.

**Comment by pmartelletti** [comment]
but again, I think the purpose of the project if for projector, not for event sourced models, so I think is out of the scope of it. But just wanted to be sure.

**Comment by 36864** [comment]
You can already sort-of do this by just querying the stored_events table. 
You could do something like 
```
$events = StoredEvent::where('event_properties->model_uuid', $uuid)->whereDate('created_at', '<', $date_limit)->get();

Model $model = new Model();
foreach($events as $event) {
 do_event_action($model, $event);
}
```

The thing is, events need not necessarily correlate directly with an action upon a model. In most cases you will probably have a projector that translates events into models, but that's not a requirement of every application. 
You may also have several projectors that translate an event into one or more models. 
There may also be models that are modified by events that don't contain their uuid or any reference to them at all. Consider a statistics model that keeps track of how many models had their states changed twice in one day. There's no way to determine if an event should change that model without querying every event that happened in the same day.

**Comment by sebastiandedeyne** [comment]
> but again, I think the purpose of the project if for projector, not for event sourced models, so I think is out of the scope of it. But just wanted to be sure.

Aren't event sourced models essentially projections? 

You can do whatever you want in the projectors, be it in-memory or some database transaction. I understand your in-memory case now, but I don't think it affects our rebuild functionality.

**Comment by pmartelletti** [comment]
@sebastiandedeyne yeah, they are kind of projections. Problem is, there's no way (out of the box, at least) to retrieve only events for a given uuid, so that I can rebuild the state of a model based on that events.

**Comment by 36864** [comment]
@pmartelletti That's because there is absolutely no requirement for an event to even have a uuid.

What you could do is have a projector that doesn't automatically handle events, but that you could instantiate, define some parameters (as in `new ObjectRebuildProjector($uuid, now()->subDay()), and then replay events for only that projector.
In my project I have a history projector which only handles events up to a specific ID, but you could easily adapt it to work on dates and filter by model uuids. If you'd like, take a look at my HistoryProjector, as well as my history controller which uses it:

https://github.com/36864/Event-Sourced-Task-Lists/blob/master/app/Projectors/HistoryProjector.php
https://github.com/36864/Event-Sourced-Task-Lists/blob/master/app/Http/Controllers/History/Controller.php

**Comment by freekmurze** [comment]
Currently we have no plans to add in-memory replay to the package as I think it's not really needed for simple event sourcing. If you need it, take a look at alternative ES packages. 

If there's a simple way to add this to the package, feel free to submit a fully tested and documented PR for me to review.
