### ISSUE TITLE
replaying events does not use custom 'stored_event_model'

### ISSUE THREAD

**Issue by lostdreamer** [spatie/laravel-event-projector#80]
When using a custom StoredEvent model (and correct setup in the config), while replaying Events, it will still use the (hard coded) Spatie\EventProjector\Models\StoredEvent class.

I was using a custom class for auto encrypting / decrypting of the payload, which fails during replay when the default StoredEvent is trying to unserialize the encrypted data.

Spatie\EventProjector\Console\Concerns\ReplaysEvents.php should check the config and use the class that is setup in there instead of using 'Spatie\EventProjector\Models\StoredEvent.php'

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this!

**Comment by freekmurze** [comment]
Quickly fixed it myself in `v1.0.4`
