### ISSUE TITLE
Specify a DB Connection to find Stored Events

### ISSUE THREAD

**Issue by AdrianB93** [spatie/laravel-event-projector#82]
**Context:**

I'm working on an app where it makes sense to take a multi-tenant approach. I figured it may be optimal if I store each of the tenants' events in their own database. It also could make it easier down the road to handle some of the clients' events in seperate or dedicated event queues.

**Problem:**

I noticed you can't specify a database connection on the commands.

**Solution:**

I can solve the issue for storing events _(`StoredEvent@getConnectionName` should set a tenants connection if the event is in this list of events.)_

I can solve the issue for projecting because the models will be set to the tenant connection.

However, with the current implementation, is there a way I can specify a connection for the commands so they know where to find the stored events, or does this need to be PR'd in?

**Question:**

Do you think this is worth doing/solving? For my use case, there is a clear seperation of data _(clients don't interact with one-another.)_ I'm not sure how performant event projection will be over time using a single event queue between many clients _(as new projectors are created.)_

**Comment by freekmurze** [comment]
Bit of a longshot but couldn't you dynamically change the db name in a service provider of your own?

```
config()->set('database.default', $dbName);
```

**Comment by AdrianB93** [comment]
Thank you. It seems very obvious now that I see it, I guess I couldn't think of it because I needed the main connection still. ¯\\_(ツ)_/¯

This worked very well for me:

```php
$this->onTenantConnection($tenant, function () {
    $this->call('event-projector:replay');
});

protected function onTenantConnection($tenant, $callback)
{
    $this->tenantManager->setTenant($tenant);
    config()->set('database.default', 'tenant');
    return tap($callback(), function () {
        config()->set('database.default', 'main');
    });
}
```
