### ISSUE TITLE
Question: retrieving historical data

### ISSUE THREAD

**Issue by DiederikvandenB** [spatie/laravel-event-projector#86]
Hi,

We have been using LEP for a while now and we are really loving it. We are running in to a little challenge right now though and we are curious to hear how you guys (and girls) would solve this.

Basically, we have a few tasklists in our application. These tasklists contain individual tasks, and a tasklist is always started and ended on the same day. The tasklists are recurring, meaning they can/have to be completed every day.

In our current setup, we have a `tasklists` table which represents the current state of the application. However, we want to retain information of tasklists that have seen user interaction in the past. Take this example:

1. User creates tasklist "Clean living room" on 01-01-2018
2. User adds 3 tasks to the tasklist on 01-01-2018
3. User renames tasklist to "Clean all living rooms" on 07-01-2018
4. User adds another 2 tasks to the tasklist on 10-01-2018

Now, if an admin wants to see the details of a tasklist on a specific date, we obviously cannot use the current state from the `tasklists` table, as for instance the name of the tasklist has changed. We want to serve the user with the data that was the current state on the day they are 

We are contemplating adding a `tasklist_history` table, projected by LEP, which we can then use to query the exact state of a model on a specific date. However, as our user base grows, this table will become huge. Furthermore, simple tasks such as retrieving basic fields from the database can get super cumbersome (imagine the code below for all fields of a table, for all your models):

``` php
public function getNameAttribute()
{
    if ($this->relationLoaded('history') {
        return $this->history->name;
    }

    return $this->name;
}
```

Obviously, we can reduce this duplicate code by extending the base Model class, but before doing that we wanted some more input from you guys.

Cheers!

**Comment by 36864** [comment]
This is a perfect example of a use case for snapshots.

While they're not supported, the best option is to have a historical projector that maintains historical versions of models.

The "pure" way would be to replay all the events up to the desired date, but that's obviously impractical with even a moderate data set.

An alternative would be to query the events table directly, looking for the last event that either created or modified the task list in question before the wanted date. Saves on storage/schema complexity, but probably slower.

**Comment by DiederikvandenB** [comment]
Thanks for the info.
