### ISSUE TITLE
event streams fail when using mariaDB

### ISSUE THREAD

**Issue by mattcannon** [spatie/laravel-event-projector#88]
### Issue
Creating an event fails when using mariaDB and event streams - the following SQL error is returned:
```
...check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."field"' = ? 
```

Streaming events fails on mariaDB due to the `->` shorthand for `JSON_EXTRACT` - this exists in mysql but not in mariaDB.

### Possible Solution
This may be solved by changing occurrences of 

```php
->where("event_properties->{$whereJsonClause}", $streamValue)
```

to 

```php
->where(\DB::raw("JSON_EXTRACT(`event_properties`,{$whereJsonClause})", $streamValue)
``` 

If you are happy with this option then I can submit a PR, however may need some guidance for adding MariaDB to the travisCI test suite.

**Comment by freekmurze** [comment]
I'm going to leave this as it is for now. I only need MySQL myself and like that clean syntax.

Feel free to fork our code and maintain a compatible version yourself.
