### ISSUE TITLE
Laravel 5.7 fails test

### ISSUE THREAD

**Issue by DiederikvandenB** [spatie/laravel-event-projector#90]
Hi,

Due to the recent bump to Laravel 5.7, tests are now partially failing for this package. Seeing the [build logs](https://travis-ci.org/spatie/laravel-event-projector/builds/424424147), the tests continue to work when installing using `--prefer-lowest`.

I'd submit a PR myself, but I don't know which strategy you'd prefer. Do you want to continue supporting 5.6< or not?

**Comment by freekmurze** [comment]
If it's not too hard I'd like keep supporting L5.6. But if the code is more readable when only supporting L5.7, I wouldn't mind dropping support for L5.6
