### ISSUE TITLE
Using ID instead of UUID's

### ISSUE THREAD

**Issue by nycooookie** [spatie/laravel-event-projector#91]
Hi!
This is not really an issue, more of a question.

---

Like some other people I was wondering why using UUID seemed necessary. And as far as I understood the (only?) issue was that some identifier to refer to the object needs to be known even before the object is created.
What if we instead checked for the next auto-generated ID and used that to generate the object and later refer to it? Of course this would be done in a transaction to avoid race conditions.

What do you think, do you see any issues related to event sourcing?
I [cloned](https://github.com/nycooookie/laravel-event-projector-demo-app) your sample repo and adjusted it to use ID's instead of UUID's, and it seems to be working so far, but maybe I missed some use case (the only interesting change is in `App\Account.php`, I copied the snipped below).

Would be glad for feedback / opinions!

```php
public static function createWithAttributes(array $attributes)
    {
        $account = DB::transaction(function () use ($attributes) {

            // Fetch the next ID
            $result = DB::select('show table status where name = ?', ['accounts'])[0];
            $id = $result->Auto_increment;

            // Generate the object by using the ID instead of UUID
            $attributes['id'] = $id;
            event(new AccountCreated($attributes));

            return Account::find($id);
        });

        return $account;
    }
```

**Comment by 36864** [comment]
We talked about this in #73, please read through that discussion, but feel free to reply here with any additional questions you might have.

**Comment by nycooookie** [comment]
I read the discussion but the replies are under the assumption that the ID is not given since it will be generated by the DB. Here I try to avoid this by explicitly setting the ID _before_ creating the object in the DB.

You pose the following example:
> As an example, let's say you have an app that lets users undo their last action. Consider the following sequence of events:
> 
> * A user presses the "create beer" button, which generates a `BeerCreated` event.
> * Before your projector has a chance to process that, the user regrets their decision and presses the "undo" button.
> * Your app checks the last event that was generated by that user and generates the opposite event, `BeerDeleted`.
> 
> At this point, the new beer doesn't exist in any tables yet, so it doesn't have an auto-incremented id. If you didn't give it a uuid, there is no way to know which beer the `BeerDeleted` event is supposed to delete.

As far as I see the create must not be queued, since this would violate the transactional part. If the create happens synchronously the above scenario would work as expected (since the app knows the ID in advance), correct?

**Comment by freekmurze** [comment]
@nycooookie 

> If the create happens synchronously the above scenario would work as expected (since the app knows the ID in advance), correct?

Seems correct.
