### ISSUE TITLE
EventHandlerCollection is missing `use Spatie\EventProjector\Exceptions\InvalidEventHandler;`

### ISSUE THREAD

**Issue by eithed** [spatie/laravel-event-projector#92]
Hi,

I've been following the tutorial (https://docs.spatie.be/laravel-event-projector/v1/basic-usage/handling-side-effects-using-reactors) and after adding the Reactor I've noticed a fatal error:

`Class 'Spatie\EventProjector\EventHandlers\InvalidEventHandler' not found` in EventHandlerCollection.php:29

to which, after debugging, I've found that there's no inclusion of `Spatie\EventProjector\Exceptions\InvalidEventHandler`, but it's being used, thus the error.

Adding the inclusion per `use Spatie\EventProjector\Exceptions\InvalidEventHandler;` solves the issue.

---

I've stumbled upon this as in tutorial `class BigAmountAddedReactor` doesn't implement `EventHandler` nor `use HandlesEvents`. The example files in `https://github.com/spatie/laravel-event-projector-demo-app/blob/master/app/Reactors/BigAmountAddedReactor.php` are correct.

Cheers!

**Comment by sebastiandedeyne** [comment]
Thanks for the heads up!
