### ISSUE TITLE
The steps to replay events in tutorial are incorrect

### ISSUE THREAD

**Issue by eithed** [spatie/laravel-event-projector#93]
Hi,

I'm following the tutorial on replaying the events (https://docs.spatie.be/laravel-event-projector/v1/basic-usage/handling-side-effects-using-reactors) - per the example:

```
If you truncate the accounts table and rebuild the contents with

php artisan event-projector:replay

no mail will be sent.
```

Unfortunately, afrter truncating the accounts table and running the command I'm getting following output:

```
Are you sure you want to replay events to all projectors? (yes/no) [no]:
 > yes

There are no events to replay.
There are no events to replay
```

After debugging, to properly replay the events I've had to empty `projector_statuses` table (which I suspect stores the status of the latest event that was handled by given projector). Afterwards running `php artisan event-projector:replay` correctly outputs:

```
Replaying all events...

 2/2 [============================] 100%

All done!
```

Cheers!

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. I corrected the docs.
