### ISSUE TITLE
projector_statuses table not updating when executing projector from redis queue

### ISSUE THREAD

**Issue by algm** [spatie/laravel-event-projector#96]
Hello!

First of all thanks for the great work.

I am having an issue with the queued projectors. If I use the sync driver everything works fine, but when I set the driver to use the redis connection, the projector_statuses table does not get updated after the projector is executed. 

I have tried to debug the issue myself but I don't have enough knowledge of the codebase to do it :(

I am using Laravel Horizon to handle the queues.

**Comment by fgilio** [comment]
It's working OK for us. We also use Redis and Horizon.

**Comment by algm** [comment]
Seems like some missconfiguration between my horizon and docker. Closing, thank you!
