### ISSUE TITLE
Queues vs. Streams

### ISSUE THREAD

**Issue by Ben52** [spatie/laravel-event-projector#99]
I'm trying to understand when to use streams, and when to use a queue to process events.
If all the incoming events are placed on a queue, and processed one at a time, is there any reason to use different streams? Maybe I'm not getting the point of streams, but from the docs, it sounds like they are for preventing race conditions with processing events concurrently. If they are all in a single queue though, is this a concern?

**Comment by freekmurze** [comment]
The streams are primarly intended to avoid race conditions when not using queues. Some more info on the subject here: https://docs.spatie.be/laravel-event-projector/v1/basic-usage/making-sure-events-get-handled-in-the-right-order
